title: pygimli_ert
application domain: 37 Earth Sciences -> 3706 Geophysics -> 370602 Electrical And Electromagnetic Methods in Geophysics -> Electircal resistivity tomography
description: description 123blabla?
method:
  pygimli_ert.ipynb: 
    - CoFI -> Parameter Estimation -> Optimization -> Non-linear -> scipy.optimize.minimize -> trust-exact

 
             