notebook:
  - title: fmm tomography
    application domain: 37 Earth Sciences -> 3706 Geophysics -> 370602 -> Electircal resistivity tomography
    description: description 123blabla?
    file_to_parse:
      - 

# skip first one files in file to parse
      