name: cofi_env
dependencies:
  - python=3.10
  - jupyterlab>=3
  - numpy>=1.18
  - scipy>=1.0.0
  - matplotlib>=3.5.0
  - conda-forge::nodejs>=12
  - gimli::pygimli
  - pip
  - pip:
    - cofi>=0.1.2.dev6
    - ipywidgets>=7.7.0
    - watermark>=2.3.0
