title: pygimli_dcip
application domain: 37 Earth Sciences -> 3706 Geophysics -> 370602 Electrical And Electromagnetic Methods in Geophysics -> Direct Current And Induced Polarization
description: description 123blabla?
method:
  - pygimli_dcip.ipynb: 
    - CoFI -> Parameter Estimation -> Optimization -> Non-linear -> pytorch.optim -> RAdam
    - CoFI -> Parameter Estimation -> Optimization -> Non-linear -> scipy.optimize.minimize -> trust-ncg
  - pygimli_dcip_century_tri_mesh.ipynb: 
    - CoFI -> Parameter Estimation -> Optimization -> Non-linear -> scipy.optimize.minimize -> trust-ncg

 
                          
      