name: Generate sphinx-gallery scripts from notebooks

on:
  workflow_dispatch:
#   push:
#     branches: main
#     paths:
#       - 'notebooks/**'
  schedule:
    - cron: '54 4 * * *'


jobs:
  generate_scripts:
    name: Generate scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          sudo apt-get install pandoc
          pip install pypandoc
     
      - name: Add/Update badges
        uses: trsvchn/colab-badge-action@v4
        with:
          verbose: true
 
      - name: Run _ipynb_to_gallery.py
        run: |
          python utils/sphinx_gallery/ipynb_to_gallery.py all
          
      - name: Set git config
        continue-on-error: true
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
      - name: Commit changes to notebooks
        continue-on-error: true
        run: |
          git add notebooks/*
          git commit -m "chore: added badges to colab in notebooks/"

      - name: Commit changes to scripts
        continue-on-error: true
        run: |
          git add scripts/*
          git commit -m "chore: update scripts/"
          
      - name: Push back to repo
        run: |
          git status
          git push
